config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  resources :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def index
		@articles = Article.all
	end
	
	def new 
		@article = Article.new
	end
	
	def create
		
		@article = Article.new(params.require(:article).permit(:title, :body))
		
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end
	
	def show
		@article = Article.find(params[:id])
	end
	
	def edit
		@article = Article.find(params[:id])
	end
	
	def update
		@article = Article.find(params[:id])
		
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path 
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :article, url: articles_path do |f| %> 

	<% if @article.errors.any? %> 
		<h2><%= pluralize(@article.errors.count, "errors")  %> 
		prohibited the article being saved </h2>  
	
		<ul> 
			<% @article.errors.full_messages.each do |msg| %> 
				<li> <%= msg %> </li>
			<% end %>
		</ul>   
	<% end %>
	
	
	<p> 
		<%= f.label :title  %> 
		<%= f.text_field :title %> 
	</p> 
	
	<p>
	<%= f.label :body %>
	<%= f.text_area :body %> 
	</p>
	
	<%= f.submit %>
<% end %> 

<%= Math::cos(2) %>

<%= link_to "Back", articles_path %>

app/views/articles/edit.html.erb
<h2> Edit Article </h2> 

<%= render 'form' %> 

app/views/articles/index.html.erb
<table> 
	<tr> 
		<th> Title </th>
		<th> Body </th>
	</tr> 
<%  @articles.each do |article| %> 
	<tr> 
		<td> <%= article.title %> </td>
		<td> <%= article.body %> </td> 
		<td>  <%= link_to "Edit", edit_article_path(article) %> </td> 
		<td> <%= link_to "Show", article %> </td>
		<td><%= link_to 'Destroy', article_path(article),
			method: :delete,
			data: { confirm: 'Are you sure?' } %></td>


	</tr>
<% end %> 

</table>
<%= link_to "New Article", new_article_path %> 

app/views/articles/new.html.erb
<h2>  New Article </h2>

<%= render 'form' %> 

app/views/articles/show.html.erb
<p> 
<strong> Title: </strong>
<%= @article.title %>
</p> 
<p>
<strong> Body: </strong>
<%= @article.body %> 
</p>

<%= link_to "Back", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogneweve</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Articles", articles_path %>